import 'com.iwhalecloud.bss.magic.script.MagicScript'
import 'com.iwhalecloud.bss.magic.script.MagicScript' as t1
import com.iwhalecloud.bss.magic.script.MagicScript as t2
import runtime.com.iwhalecloud.bss.magic.script.RuntimeContext
import 'java.text.*'
import java.io.*;
return
    t1 == MagicScript
    && t2 == t1
    && DateFormat.LONG == 1
    && File::string == 'class java.io.File'
    && RuntimeContext::string == 'class runtime.com.iwhalecloud.bss.magic.script.RuntimeContext'